// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Storykeeper.Api.Data;

#nullable disable

namespace Storykeeper.Api.Data.Migrations
{
    [DbContext(typeof(StorykeeperDbContext))]
    [Migration("20261010060848_ActiveSessionStoryTurnHistory")]
    partial class ActiveSessionStoryTurnHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Storykeeper.Api.Domain.AdventureDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActivatedQuestId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("GenerationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentPreferences")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionLengthMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedQuestId")
                        .IsUnique()
                        .HasFilter("ActivatedQuestId IS NOT NULL");

                    b.HasIndex("CampaignId", "UpdatedAtUtc");

                    b.ToTable("AdventureDrafts", t =>
                        {
                            t.HasCheckConstraint("CK_AdventureDrafts_GenerationNumber", "GenerationNumber >= 1");

                            t.HasCheckConstraint("CK_AdventureDrafts_SessionLength", "SessionLengthMinutes BETWEEN 15 AND 180");
                        });
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.CampaignBible", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentSituation")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("WorldDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .IsUnique();

                    b.ToTable("CampaignBibles", t =>
                        {
                            t.HasCheckConstraint("CK_CampaignBibles_Version", "Version >= 1");
                        });
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.CampaignBibleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ActivatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasMaxLength(30000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceDraftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceDraftId")
                        .IsUnique()
                        .HasFilter("SourceDraftId IS NOT NULL");

                    b.HasIndex("CampaignId", "Version")
                        .IsUnique();

                    b.ToTable("CampaignBibleVersions", t =>
                        {
                            t.HasCheckConstraint("CK_CampaignBibleVersions_Version", "Version >= 1");
                        });
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.CampaignBrief", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CampaignLengthSessions")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exclusions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Inclusions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SafetyBoundaries")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SafetySettings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionLengthMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoryIdea")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CampaignBriefs");
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.CampaignContinuityRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewContent")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousContent")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceSessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "ChangedAtUtc");

                    b.HasIndex("CampaignId", "RecordType", "RecordId");

                    b.ToTable("CampaignContinuityRevisions");
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.CampaignDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignBriefId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasMaxLength(30000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("GenerationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignBriefId");

                    b.HasIndex("CampaignId");

                    b.ToTable("CampaignDrafts");
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.CampaignFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Importance")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "SourceSessionId");

                    b.ToTable("CampaignFacts", t =>
                        {
                            t.HasCheckConstraint("CK_CampaignFacts_Importance", "Importance BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.CampaignSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LowFright")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SafetySettings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .IsUnique();

                    b.ToTable("CampaignSettings");
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.CheckResolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsequenceCategory")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ForwardProgressRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeartsAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeartsBefore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Risky")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Roll")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RollSource")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SparkleBonus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SparkleTokenSpent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SparkleTokensAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SparkleTokensBefore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Strength")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("StrengthBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Target")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "HeroId");

                    b.HasIndex("CampaignId", "SessionId");

                    b.ToTable("CheckResolutions", t =>
                        {
                            t.HasCheckConstraint("CK_CheckResolutions_Roll", "Roll BETWEEN 1 AND 20");

                            t.HasCheckConstraint("CK_CheckResolutions_Target", "Target IN (8, 12, 16)");
                        });
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Hearts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("SparkleTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("'[]'");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "PartyId");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "HeroId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Npc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "LocationId");

                    b.ToTable("Npcs");
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId")
                        .IsUnique();

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdventurePlanJson")
                        .HasMaxLength(12000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionLengthMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Quests", t =>
                        {
                            t.HasCheckConstraint("CK_Quests_SessionLength", "SessionLengthMinutes IS NULL OR SessionLengthMinutes BETWEEN 15 AND 180");
                        });
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Relationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubjectType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Reward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HeroId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClaimed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "HeroId");

                    b.ToTable("Rewards");
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentInstruction")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "SessionNumber")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.StoryBeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActingHeroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CheckResolutionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ChronologyEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Narration")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NpcDialogueJson")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId", "SessionId", "Id")
                        .IsUnique();

                    b.HasIndex("CampaignId", "SessionId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("StoryBeats");
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.AdventureDraft", b =>
                {
                    b.HasOne("Storykeeper.Api.Domain.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.CampaignBible", b =>
                {
                    b.HasOne("Storykeeper.Api.Domain.Campaign", null)
                        .WithOne("Bible")
                        .HasForeignKey("Storykeeper.Api.Domain.CampaignBible", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.CampaignBibleVersion", b =>
                {
                    b.HasOne("Storykeeper.Api.Domain.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Storykeeper.Api.Domain.CampaignDraft", null)
                        .WithMany()
                        .HasForeignKey("SourceDraftId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.CampaignContinuityRevision", b =>
                {
                    b.HasOne("Storykeeper.Api.Domain.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.CampaignDraft", b =>
                {
                    b.HasOne("Storykeeper.Api.Domain.CampaignBrief", "CampaignBrief")
                        .WithMany("Drafts")
                        .HasForeignKey("CampaignBriefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Storykeeper.Api.Domain.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CampaignBrief");
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.CampaignFact", b =>
                {
                    b.HasOne("Storykeeper.Api.Domain.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Storykeeper.Api.Domain.Session", null)
                        .WithMany("Facts")
                        .HasForeignKey("CampaignId", "SourceSessionId")
                        .HasPrincipalKey("CampaignId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.CampaignSettings", b =>
                {
                    b.HasOne("Storykeeper.Api.Domain.Campaign", null)
                        .WithOne("Settings")
                        .HasForeignKey("Storykeeper.Api.Domain.CampaignSettings", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.CheckResolution", b =>
                {
                    b.HasOne("Storykeeper.Api.Domain.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Storykeeper.Api.Domain.Hero", null)
                        .WithMany()
                        .HasForeignKey("CampaignId", "HeroId")
                        .HasPrincipalKey("CampaignId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Storykeeper.Api.Domain.Session", null)
                        .WithMany("CheckResolutions")
                        .HasForeignKey("CampaignId", "SessionId")
                        .HasPrincipalKey("CampaignId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Hero", b =>
                {
                    b.HasOne("Storykeeper.Api.Domain.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Storykeeper.Api.Domain.Party", null)
                        .WithMany("Heroes")
                        .HasForeignKey("CampaignId", "PartyId")
                        .HasPrincipalKey("CampaignId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.InventoryItem", b =>
                {
                    b.HasOne("Storykeeper.Api.Domain.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Storykeeper.Api.Domain.Hero", null)
                        .WithMany("Inventory")
                        .HasForeignKey("CampaignId", "HeroId")
                        .HasPrincipalKey("CampaignId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Location", b =>
                {
                    b.HasOne("Storykeeper.Api.Domain.Campaign", null)
                        .WithMany("Locations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Npc", b =>
                {
                    b.HasOne("Storykeeper.Api.Domain.Campaign", null)
                        .WithMany("Npcs")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Storykeeper.Api.Domain.Location", null)
                        .WithMany()
                        .HasForeignKey("CampaignId", "LocationId")
                        .HasPrincipalKey("CampaignId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Party", b =>
                {
                    b.HasOne("Storykeeper.Api.Domain.Campaign", null)
                        .WithOne("Party")
                        .HasForeignKey("Storykeeper.Api.Domain.Party", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Quest", b =>
                {
                    b.HasOne("Storykeeper.Api.Domain.Campaign", null)
                        .WithMany("Quests")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Relationship", b =>
                {
                    b.HasOne("Storykeeper.Api.Domain.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Reward", b =>
                {
                    b.HasOne("Storykeeper.Api.Domain.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Storykeeper.Api.Domain.Hero", null)
                        .WithMany()
                        .HasForeignKey("CampaignId", "HeroId")
                        .HasPrincipalKey("CampaignId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Session", b =>
                {
                    b.HasOne("Storykeeper.Api.Domain.Campaign", null)
                        .WithMany("Sessions")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.StoryBeat", b =>
                {
                    b.HasOne("Storykeeper.Api.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("CampaignId", "SessionId")
                        .HasPrincipalKey("CampaignId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Campaign", b =>
                {
                    b.Navigation("Bible");

                    b.Navigation("Locations");

                    b.Navigation("Npcs");

                    b.Navigation("Party");

                    b.Navigation("Quests");

                    b.Navigation("Sessions");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.CampaignBrief", b =>
                {
                    b.Navigation("Drafts");
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Hero", b =>
                {
                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Party", b =>
                {
                    b.Navigation("Heroes");
                });

            modelBuilder.Entity("Storykeeper.Api.Domain.Session", b =>
                {
                    b.Navigation("CheckResolutions");

                    b.Navigation("Facts");
                });
#pragma warning restore 612, 618
        }
    }
}
